---
title: "BellaBeat_Viz"
author: "Qunyquekya Wallis"
date: '2022-06-30'
output: html_document
---

#plotting activity versus calories-sedentary
ggplot(data = daily_activity, aes(x =SedentaryMinutes, y = Calories)) + 
  geom_point()+ geom_smooth(method=lm)+
  ggtitle("Calories vs. Sedentary Minutes") +
  xlab("Minutes") + ylab("Calories")+ theme(plot.title = element_text(face="bold"))

#plotting activity versus calories-light
ggplot(data = daily_activity, aes(x =LightlyActiveMinutes, y = Calories)) + 
  geom_point()+ geom_smooth(method=lm)+
  ggtitle("Calories vs. Lightly Active Minutes") +
  xlab("Minutes") + ylab("Calories")+ theme(plot.title = element_text(face="bold"))

#plotting activity versus calories-fair
ggplot(data = daily_activity, aes(x =FairlyActiveMinutes, y = Calories)) + 
  geom_point()+ geom_smooth(method=lm)+
  ggtitle("Calories vs. Fairly Active Minutes") +
  xlab("Minutes") + ylab("Calories")+ theme(plot.title = element_text(face="bold"))

#plotting activity versus calories-very
ggplot(data = daily_activity, aes(x =VeryActiveMinutes, y = Calories)) + 
  geom_point()+ geom_smooth(method=lm)+
  ggtitle("Calories vs. Very Active Minutes") +
  xlab("Minutes") + ylab("Calories") + theme(plot.title = element_text(face="bold"))

#calories burned versus steps taken
ggplot(data = daily_activity, aes(x =TotalSteps, y = Calories)) + 
  geom_point()+ geom_smooth(method=lm)+
  ggtitle("Calories vs. Total Steps Taken") +
  xlab("Steps") + ylab("Calories")+ theme(plot.title = element_text(face="bold"))

#calories versus total distance
ggplot(data = daily_activity, aes(x =TotalDistance, y = Calories)) + 
  geom_point()+ geom_smooth(method=lm)+
  ggtitle("Calories vs. Total Distance") +
  xlab("Distance (km)") + ylab("Calories") + theme(plot.title = element_text(face="bold"))

#Entries per day of the week to show when device is worn the most 
# put entries in chronological order
ggplot(data = daily_activity)+
  stat_count(mapping = aes(x = Weekday))+
  ggtitle("Entries Per Day of the Week") +
  xlab("Days of the Week") + ylab("Entries") + theme(plot.title = element_text(face="bold"))+
  scale_x_discrete(limits = c("Monday", "Tuesday", "Wednesday", "Thursday","Friday", "Saturday","Sunday"))

